with open('/Users/varul18/Desktop/F1/Season2019/DriverGrid_Seas2019.txt','w') as f:
    f.write('List of Drivers for 2019 Season')
    f.write('\n')
    f.write('\n')
    f.write('Name                Nationality          Car')
    f.write('\n')
    f.write('\n')
    f.write('Lewis Hamilton         GBR               MERCEDES  " Winner 👑 "')
    f.write('\n')
    f.write('Valtteri Bottas        FIN               MERCEDES')
    f.write('\n')
    f.write('Max Verstappen         NED               RED BULL RACING HONDA')
    f.write('\n')
    f.write('Charles Leclerc        MON               FERRARI')
    f.write('\n')
    f.write('Sebastian Vettel       GER               FERRARI')
    f.write('\n')
    f.write('Carlos Sainz           ESP               MCLAREN RENAULT')
    f.write('\n')
    f.write('Pierre Gasly           FRA               SCUDERIA TORO ROSSO HONDA')
    f.write('\n')
    f.write('Alexander Albon        THA               RED BULL RACING HONDA')
    f.write('\n')
    f.write('Daniel Ricciardo       AUS               RENAULT')
    f.write('\n')
    f.write('Sergio Perez           MEX               RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('Lando Norris           GBR               MCLAREN RENAULT')
    f.write('\n')
    f.write('Kimi Räikkönen         FIN               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Daniil Kvyat           RUS               SCUDERIA TORO ROSSO HONDA')
    f.write('\n')
    f.write('Nico Hulkenberg        GER               RENAULT')
    f.write('\n')
    f.write('Lance Stroll           CAN               RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('Kevin Magnussen        DEN               HAAS FERRARI')
    f.write('\n')
    f.write('Antonio Giovinazzi     ITA               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Romain Grosjean        FRA               HAAS FERRARI')
    f.write('\n')
    f.write('Robert Kubica          POL               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('George Russell         GBR               WILLIAMS MERCEDES')


with open('/Users/varul18/Desktop/F1/Season2020/DriverGrid_Seas2020.txt','w') as f:
    f.write('List of Drivers for 2020 Season')
    f.write('\n')
    f.write('\n')
    f.write('Name                Nationality          Car')
    f.write('\n')
    f.write('\n')
    f.write('Lewis Hamilton         GBR               MERCEDES  " Winner 👑 "')
    f.write('\n')
    f.write('Valtteri Bottas        FIN               MERCEDES')
    f.write('\n')
    f.write('Max Verstappen         NED               RED BULL RACING HONDA')
    f.write('\n')
    f.write('Charles Leclerc        MON               FERRARI')
    f.write('\n')
    f.write('Sebastian Vettel       GER               FERRARI')
    f.write('\n')
    f.write('Carlos Sainz           ESP               MCLAREN RENAULT')
    f.write('\n')
    f.write('Pierre Gasly           FRA               ALPHATAURI HONDA')
    f.write('\n')
    f.write('Alexander Albon        THA               RED BULL RACING HONDA')
    f.write('\n')
    f.write('Daniel Ricciardo       AUS               RENAULT')
    f.write('\n')
    f.write('Sergio Perez           MEX               RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('Lando Norris           GBR               MCLAREN RENAULT')
    f.write('\n')
    f.write('Kimi Räikkönen         FIN               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Daniil Kvyat           RUS               ALPHATAURI HONDA')
    f.write('\n')
    f.write('Nico Hulkenberg        GER               RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('Lance Stroll           CAN               RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('Kevin Magnussen        DEN               HAAS FERRARI')
    f.write('\n')
    f.write('Antonio Giovinazzi     ITA               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Romain Grosjean        FRA               HAAS FERRARI')
    f.write('\n')
    f.write('Nicholas Latifi        CAN               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('George Russell         GBR               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('Esteban Ocon           FRA               RENAULT')
    f.write('\n')
    f.write('Jack Aitken            GBR               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('Pietro Fittipaldi      BRA               HAAS FERRARI')


with open('/Users/varul18/Desktop/F1/Season2021/DriverGrid_Seas2021.txt','w') as f:
    f.write('List of Drivers for 2021 Season')
    f.write('\n')
    f.write('\n')
    f.write('Name                Nationality          Car')
    f.write('\n')
    f.write('\n')
    f.write('Max Verstappen         NED               RED BULL RACING HONDA  " Winner 👑 "')
    f.write('\n')
    f.write('Lewis Hamilton         GBR               MERCEDES')
    f.write('\n')
    f.write('Valtteri Bottas        FIN               MERCEDES')
    f.write('\n')
    f.write('Sergio Perez           MEX               RED BULL RACING HONDA')
    f.write('\n')
    f.write('Carlos Sainz           ESP               FERRARI')
    f.write('\n')
    f.write('Lando Norris           GBR               MCLAREN MERCEDES')
    f.write('\n')
    f.write('Charles Leclerc        MON               FERRARI')
    f.write('\n')
    f.write('Daniel Ricciardo       AUS               MCLAREN MERCEDES')
    f.write('\n')
    f.write('Pierre Gasly           FRA               ALPHATAURI HONDA')
    f.write('\n')
    f.write('Fernando Alonso        ESP               ALPINE RENAULT')
    f.write('\n')
    f.write('Esteban Ocon           FRA               ALPINE RENAULT')
    f.write('\n')
    f.write('Sebastian Vettel       GER               ASTON MARTIN MERCEDES')
    f.write('\n')
    f.write('Lance Stroll           CAN               ASTON MARTIN MERCEDES')
    f.write('\n')
    f.write('Yuki Tsunoda           JPN               ALPHATAURI HONDA')
    f.write('\n')
    f.write('George Russell         GBR               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('Kimi Räikkönen         FIN               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Nicholas Latifi        CAN               WILLIAMS MERCEDES')
    f.write('\n')
    f.write('Antonio Giovinazzi     ITA               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Mick Schumacher        GER               HAAS FERRARI')
    f.write('\n')
    f.write('Robert Kubica          POL               ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('Nikita Mazepin         RAF               HAAS FERRARI')