with open('/Users/varul18/Desktop/F1/Season2019/Season_2019_Schedule.txt','w') as f:
    f.write('F1 2019 Race Schedule')
    f.write('\n')
    f.write('\n')
    f.write('Venue           Date')
    f.write('\n')
    f.write('\n')
    f.write('Australia       17 MAR 2019')
    f.write('\n')
    f.write('Bahrain         31 MAR 2019')
    f.write('\n')
    f.write('China           14 APR 2019')
    f.write('\n')
    f.write('Azerbaijan      28 APR 2019')
    f.write('\n')
    f.write('Spain           12 MAY 2019')
    f.write('\n')
    f.write('Monaco          26 MAY 2019')
    f.write('\n')
    f.write('Canada          09 JUN 2019')
    f.write('\n')
    f.write('France          23 JUN 2019')
    f.write('\n')
    f.write('Austria         30 JUN 2019')
    f.write('\n')
    f.write('Great Britain   14 JUL 2019')
    f.write('\n')
    f.write('Germany         28 JUL 2019')
    f.write('\n')
    f.write('Hungary         04 AUG 2019')
    f.write('\n')
    f.write('Belgium         01 SEP 2019')
    f.write('\n')
    f.write('Italy           08 SEP 2019')
    f.write('\n')
    f.write('Singapore       22 SEP 2019')
    f.write('\n')
    f.write('Russia          29 SEP 2019')
    f.write('\n')
    f.write('Japan           13 OCT 2019')
    f.write('\n')
    f.write('Mexico          27 OCT 2019')
    f.write('\n')
    f.write('United States   03 NOV 2019')
    f.write('\n')
    f.write('Brazil          17 NOV 2019')
    f.write('\n')
    f.write('Abu Dhabi       01 DEC 2019')

with open('/Users/varul18/Desktop/F1/Season2020/Season_2020_Schedule.txt','w') as f:
    f.write('F1 2020 Race Schedule')
    f.write('\n')
    f.write('\n')
    f.write('Venue              Date')
    f.write('\n')
    f.write('\n')
    f.write('Austria            05 JUL 2020')
    f.write('\n')
    f.write('Styria             12 JUL 2020')
    f.write('\n')
    f.write('Hungary            19 JUL 2020')
    f.write('\n')
    f.write('Great Britain      02 AUG 2020')
    f.write('\n')
    f.write('70TH Anniversary   09 AUG 2020')
    f.write('\n')
    f.write('Spain              16 AUG 2020')
    f.write('\n')
    f.write('Belgium            30 AUG 2020')
    f.write('\n')
    f.write('Italy              06 SEP 2020')
    f.write('\n')
    f.write('Tuscany            13 SEP 2020')
    f.write('\n')
    f.write('Russia             27 SEP 2020')
    f.write('\n')
    f.write('Eifel              11 OCT 2020')
    f.write('\n')
    f.write('Portugal           25 OCT 2020')
    f.write('\n')
    f.write('Emilia Romagna     01 NOV 2020')
    f.write('\n')
    f.write('Turkey             15 NOV 2020')
    f.write('\n')
    f.write('Bahrain            29 NOV 2020')
    f.write('\n')
    f.write('Sakhir             06 DEC 2020')
    f.write('\n')
    f.write('Abu Dhabi          13 DEC 2020')

with open('/Users/varul18/Desktop/F1/Season2021/Season_2021_Schedule.txt','w') as f:
    f.write('F1 2021 Race Schedule')
    f.write('\n')
    f.write('\n')
    f.write('Venue              Date')
    f.write('\n')
    f.write('\n')
    f.write('Bahrain            28 MAR 2021')
    f.write('\n')
    f.write('Emilia Romagna     18 APR 2021')
    f.write('\n')
    f.write('Portugal           02 MAY 2021')
    f.write('\n')
    f.write('Spain              09 MAY 2021')
    f.write('\n')
    f.write('Monaco             23 MAY 2021')
    f.write('\n')
    f.write('Azerbaijan         06 JUN 2021')
    f.write('\n')
    f.write('France             20 JUN 2021')
    f.write('\n')
    f.write('Styria             27 JUN 2021')
    f.write('\n')
    f.write('Austria            04 JUL 2021')
    f.write('\n')
    f.write('Great Britain      18 JUL 2021')
    f.write('\n')
    f.write('Hungary            01 AUG 2021')
    f.write('\n')
    f.write('Belgium            29 AUG 2021')
    f.write('\n')
    f.write('Netherlands        05 SEP 2021')
    f.write('\n')
    f.write('Italy              12 SEP 2021')
    f.write('\n')
    f.write('Russia             26 SEP 2021')
    f.write('\n')
    f.write('Turkey             10 OCT 2021')
    f.write('\n')
    f.write('United States      24 OCT 2021')
    f.write('\n')
    f.write('Mexico             07 NOV 2021')
    f.write('\n')
    f.write('Brazil             14 NOV 2021')
    f.write('\n')
    f.write('Qatar              21 NOV 2021')
    f.write('\n')
    f.write('Saudi Arabia       05 DEC 2021')
    f.write('\n')
    f.write('Abu Dhabi          12 DEC 2021')