with open('/Users/varul18/Desktop/F1/Season2019/Teams_Seas2019.txt','w') as f:
    f.write('List of Teams for 2019 Season')
    f.write('\n')
    f.write('\n')
    f.write('MERCEDES')
    f.write('\n')
    f.write('RED BULL RACING HONDA')
    f.write('\n')
    f.write('FERRARI')
    f.write('\n')
    f.write('MCLAREN RENAULT')
    f.write('\n')
    f.write('SCUDERIA TORO ROSSO HONDA')
    f.write('\n')
    f.write('RENAULT')
    f.write('\n')
    f.write('RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('HAAS FERRARI')
    f.write('\n')
    f.write('WILLIAMS MERCEDES')


with open('/Users/varul18/Desktop/F1/Season2020/Teams_Seas2020.txt','w') as f:
    f.write('List of Teams for 2020 Season')
    f.write('\n')
    f.write('\n')
    f.write('MERCEDES')
    f.write('\n')
    f.write('RED BULL RACING HONDA')
    f.write('\n')
    f.write('FERRARI')
    f.write('\n')
    f.write('MCLAREN RENAULT')
    f.write('\n')
    f.write('ALPHATAURI HONDA')
    f.write('\n')
    f.write('RENAULT')
    f.write('\n')
    f.write('RACING POINT BWT MERCEDES')
    f.write('\n')
    f.write('ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('HAAS FERRARI')
    f.write('\n')
    f.write('WILLIAMS MERCEDES')


with open('/Users/varul18/Desktop/F1/Season2021/Teams_Seas2021.txt','w') as f:
    f.write('List of Teams for 2021 Season')
    f.write('\n')
    f.write('\n')
    f.write('MERCEDES')
    f.write('\n')
    f.write('RED BULL RACING HONDA')
    f.write('\n')
    f.write('FERRARI')
    f.write('\n')
    f.write('MCLAREN MERCEDES')
    f.write('\n')
    f.write('ALPHATAURI HONDA')
    f.write('\n')
    f.write('ALPINE RENAULT')
    f.write('\n')
    f.write('ASTON MARTIN MERCEDES')
    f.write('\n')
    f.write('ALFA ROMEO RACING FERRARI')
    f.write('\n')
    f.write('HAAS FERRARI')
    f.write('\n')
    f.write('WILLIAMS MERCEDES')